Prysm_libP2P_Implementation_project_proposal
eth-protocol-fellows/cohort-five pull request #272
Opened 2024-07-24 15:54 UTC by rose2221

Could you please review it @taxmeifyoucan

2024-07-24 18:04 UTC, rose2221 commented
Thanks @taxmeifyoucan ,This proposal was reviewed and contributed by everyone. After our discussions, I uploaded the final version.

2024-07-24 18:42 UTC, shyam-patel-kira requested changes

2024-07-24 18:42 UTC, shyam-patel-kira commented on projects/Prysm libP2P Implementation
> +# Prysm libP2P Implementation | Design Doc
```suggestion
# Custom golang implementation of libp2p in Prysm
```

2024-07-24 18:42 UTC, shyam-patel-kira commented on projects/Prysm libP2P Implementation
> +Custom go-libP2P implementation with specific components as used by Prysm.
```suggestion
An in-house implementation of the necessary parts of the libp2p protocol in the Prysm client
```

2024-07-24 18:42 UTC, shyam-patel-kira commented on projects/Prysm libP2P Implementation
> +The project aims to develop an in-house implementation of p2p communication library and leverage some of the core components from the existing [go-libp2p](https://github.com/libp2p/go-libp2p) librari
```suggestion
The project aims to develop an in-house implementation of p2p communication library and leverage some of the core components from the existing [go-libp2p](https://github.com/libp2p/go-libp2p) libraries. go-libP2P library(and its variants in other languages) are used by almost all consensus clients for p2p network communications among beacon chain nodes. The scope of the project enables the Prysm team to be independent of any third party for the integral components. It also allows for elimination of redundant components from go-libp2p which are not actively used, while achieving the same performance. Implementing the project also involves incorporating a deep understanding of libP2P and networking layer. 
```

2024-07-24 18:42 UTC, shyam-patel-kira commented on projects/Prysm libP2P Implementation
> +    *   the components which can be eliminated completely.
```suggestion
    *  the components which can be eliminated completely. 
```

2024-07-24 18:42 UTC, shyam-patel-kira commented on projects/Prysm libP2P Implementation
> +    *   Thanks to @MaxDav for noting some required changes in his [notes](https://hackmd.io/zIWLqRzWT76I5T_sPbJ0KA).
```suggestion
    *  Thanks to @MaxDav for noting some required changes in his [notes](https://hackmd.io/zIWLqRzWT76I5T_sPbJ0KA).
```

2024-07-24 18:42 UTC, shyam-patel-kira commented on projects/Prysm libP2P Implementation
> +* Deep dive into the p2p-interface.md from the consensus specs. Understand the theoretical aspects thoroughly.
```suggestion
- Deep dive into the p2p-interface.md from the consensus specs. Understand the theoretical aspects thoroughly.
```

2024-07-24 18:42 UTC, shyam-patel-kira commented on projects/Prysm libP2P Implementation
> +* Start examining the existing libp2p components used in the Ethereum beacon chain. Identify which components are utilized by Prysm and which are not necessary.
```suggestion
- Start examining the existing libp2p components used in the Ethereum beacon chain. Identify which components are utilized by Prysm and which are not necessary.
```

2024-07-24 18:43 UTC, shyam-patel-kira commented
Hey @rose2221, thanks for the PR, just requested some nits

2024-07-30 23:58 UTC, shyam-patel-kira approved these changes

2024-07-30 23:59 UTC, shyam-patel-kira commented
@taxmeifyoucan this can be merged now

2024-07-31 11:16 UTC, merged